// <auto-generated />
using System;
using Landen.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Landen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241025193755_Landen")]
    partial class Landen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Landen.Model.Land", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AantalInwooners")
                        .HasColumnType("int");

                    b.Property<DateTime>("AantalInwoonersDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Bnp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BnpDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EersteTaal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Gevonden")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hooftstad")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TelefoonCode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Naam", "EersteTaal", "AantalInwooners", "AantalInwoonersDatum", "Hooftstad", "TelefoonCode", "Bnp", "BnpDatum", "Gevonden")
                        .IsUnique();

                    b.ToTable("Land");
                });
#pragma warning restore 612, 618
        }
    }
}
